### ISSUE TITLE
Формат даты

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#187]
На странице добавления задачи контролы "Дата публикации" и "Дедлайн задачи" показывают дату в формате мм/дд/гг и время в формате AM/PM, что капец как неудобно. Может, правда, это зависит от локали ОС, но по идее мы ориентируемся только на российский рынок, так что все форматы должны быть российские.

**Comment by DedSec256** [comment]
У нас используется контрол с нативным временем пользователя, надо бы это поправить.

**Comment by yurii-litvinov** [comment]
А ещё, судя по всему, есть некоторые проблемы с временными зонами. Выбираю в контроле дедлайн 23:59 28-го, жму "Сохранить", дедлайн показывается как 02:59 29-го.

Вообще, аккуратна работа со временными зонами довольно критична, обучающиеся имеют свойство расползаться по всей планете, особенно летом.
