### ISSUE TITLE
Заменить везде "Домашка" на "Домашняя работа"

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#188]
Иначе Никита Юрьевич Ловягин не будет пользоваться сервисом **никогда** :)

**Comment by DedSec256** [comment]
@yurii-litvinov, а где вы встречали такую формулировку?

**Comment by DedSec256** [comment]
Исправлено в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/3728ae56a5b712e391c2d5459f851313eeedba17
