### ISSUE TITLE
Дата публикации и дедлайн --- свойства не задачи, а домашки

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#189]
Весь смысл сущности "Домашка" --- коллекция задач с общим дедлайном и датой публикации. Иначе чем мы лучше Blackboard, где чтобы добавить 6 задач в первую домашку первакам, надо было полчаса долбаться, в неудобных контролах в американском формате даты/времени выставляя дедлайны для **каждой** задачи?

**Comment by DedSec256** [comment]
@yurii-litvinov, возможны ли потенциальные сценарии, когда захочется продлить дедлайн для конкретной задачи? Думаю о том, чтобы оставить дедлайн свойством задачи, однако в UI иметь возможность указать его для всей домашей работы, после чего он применится для всех вложенных задач.

**Comment by yurii-litvinov** [comment]
Думаю на практике нет, но теоретически такое возможно, конечно. Возможность быстро выставить и поменять дедлайн для всех задач в домашке вполне ок.
