### ISSUE TITLE
Редактирование профиля должно быть на странице профиля

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#191]
Сейчас это "Редактировать данные" в главном меню, и никто никогда не догадается, что это, пока не кликнет. Хочется кнопку редактирования профиля где-то в заголовке страницы профиля, рядом с почтой.

**Comment by DedSec256** [comment]
Исправлено в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/e4fecb326bbebfa875b276df576c8fbd7a34573d
