### ISSUE TITLE
Сломанные ссылки в нотификациях

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#196]
Например, "Пользователь Роман Пожарский подал заявку на вступление в курс Программирование.". "Программирование" — это ссылка "http://courses/3"

**Comment by DedSec256** [comment]
Подозрительно, у меня в том же уведомлении нормальная ссылка (:

**Comment by DedSec256** [comment]
@yurii-litvinov, а вы какой браузер используете?

**Comment by DedSec256** [comment]
Исправлено в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/56598fa4c559ff0ac29754c01854b448102a7e1c
