### ISSUE TITLE
Личный прогресс по курсу

### ISSUE THREAD

**Issue by dltttl** [InteIIigeNET/HwProj-2.0.1#198]
Хорошо бы показывать табличку с баллами за все мои, как студента, домашки.
В данный момент приходится заходить во все домашки, смотреть сколько там давали баллов  за каждые попытки, чтобы вспомнить свой прогресс - это неудобно

**Comment by DedSec256** [comment]
Исправлено в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/dc54e7ed485467d530476378738974fef7db03fa
