### ISSUE TITLE
Время публикации и дедлайн по умолчанию

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#199]
Выбирать для домашки время публикации и дедлайн сейчас очень неудобно. Правильнее было бы для публикации время по умолчанию выставлять в полночь даты публикации, а для дедлайна — в 23:59 дня дедлайна. Более того, дата дедлайна по умолчанию может быть "дата публикации + 2 недели", чтобы в большинстве случаев можно было просто кликнуть на "добавить дедлайн" и больше ничего не выставлять.

В качестве дополнительной возможности сделать настройку для курса дефолтных времён публикации и дедлайнов (в реальной практике были случаи, когда точное время дедлайна было важно — студенты говорили, что не пойдут на пару, потому что дедлайн, и приходилось переносить дедлайн на 9:00 утра).

**Comment by DedSec256** [comment]
Настройки — всегда душно. Возможно, мы можем на основе предыдущих выставлений дедлайнов и дат публикации предложить значение по умолчанию для новой домашней работы.
