### ISSUE TITLE
Цвет ячейки с повторным сабмитом в таблице

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#200]
Лучше как в HwProj 1 бледно-жёлтым, сейчас бледно-зелёный — неотличим от первой попытки сдачи. 

Важно, потому что повторные сабмиты, как правильно, приоритетнее проверить. Поэтому, кстати, в очереди на проверку стоит также показывать номер сабмита, как делается в Blackboard.

**Comment by DedSec256** [comment]
Мы можем так же в виджете "Требуют проверки" добавлять пометку о повторной сдаче.

**Comment by DedSec256** [comment]
@yurii-litvinov, готово!
![image](https://user-images.githubusercontent.com/26364714/189547246-a172cfc1-6ce4-426d-be85-2cb854782a33.png)
![image](https://user-images.githubusercontent.com/26364714/189547255-8a757b65-2460-4353-945b-27a475eb34b3.png)
