### ISSUE TITLE
Отображать на странице оценки решения балл за предыдущую попытку

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#202]
Сейчас можно посмотреть предыдущую оценку в соседней вкладке, но кажется нетрудным отображать предыдущую оценку прямо рядом с контролом для новой оценки. Важно, чтобы не ставить оценку ниже той, что уже была

**Comment by DedSec256** [comment]
![image](https://user-images.githubusercontent.com/26364714/189771414-af732da7-0cb1-4c24-b383-3dddcbc242d5.png)
