### ISSUE TITLE
Плашка "Повторно" в очереди на проверку появляется, если студент несколько раз сдал решение ещё до первой проверки

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#205]
Речь про вот это
![image](https://user-images.githubusercontent.com/706768/189919728-8181ea7f-5db8-42e6-9ba8-1c8069ed60dc.png)

Технически он сдал дважды, так что появление плашки как бы не баг, но по смыслу боец, скорее всего, в первый раз что-то не так засабмитил и тут же исправился, так что логически это один сабмит. Более того, логически можно считать одним сабмитом все сабмиты до получения фидбэка, и учитывать это не только при выставлении плашки, но и штрафов за задачи и т.п.

**Comment by DedSec256** [comment]
это будет несложно поправить
