### ISSUE TITLE
После оценки решения открывать следующее решение из очереди на проверку

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#207]
С учётом фильтров, по возможности. 

Сейчас ставим оценку — продолжаем созерцать оцененное решение и надо кликнуть на HW и следующее решение из очереди. Что хорошо, если вы только что проверили огромную домашку по архитектуре и хотите выдохнуть и налить кофе, но плохо, если вам надо быстро проверить 60 * 4 = 240 маленьких решений со вступительного теста :)

**Comment by DedSec256** [comment]
Да, я тоже думал об этом, но пока не придумал, как сделать максимально удобно (:

**Comment by DedSec256** [comment]
Добавлено в рамках решений одной задачи
https://github.com/InteIIigeNET/HwProj-2.0.1/commit/e4fc67cd497b20cd5c8f1b82f22c72d65bd428a5

**Comment by DedSec256** [comment]
Теперь должно сортироваться в порядке записи в таблице.

**Comment by DedSec256** [comment]
Кажется, можно после оценки решения сразу переходить к следующему, без дополнительного клика на "следующее"?

**Comment by DedSec256** [comment]
Поправлено в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/30fe017da263ac28bc50464e159b2ea2a19b2c0b
