### ISSUE TITLE
"Следующее непровереннное решение", опечатка

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#210]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/706768/198982134-e2e00df9-8c13-4ed9-b47d-1fdccff6cf60.png">

**Comment by DedSec256** [comment]
![image](https://user-images.githubusercontent.com/26364714/199139496-8868c07b-ee28-42e0-9285-1eb5c5823378.png)

**Comment by DedSec256** [comment]
Исправлено, доедет со следующим деплоем.
