### ISSUE TITLE
Различать понятия "Домашняя работа" и "Тест"

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#214]
- Домашняя работа сдаётся в несколько попыток, имеет максимальный и текущий балл, и ячейка с оценкой "зеленеет", когда эти баллы встречаются
- Тест — это "одноразовая" активность, попытка только одна (и поэтому не показывается в UI), и балл за тест окончательный. Клетка "зеленеет", если выставлена хоть какая-то оценка (или может быть даже цветовой шкалой от красного до зелёного, в зависимости от близости оценки к максимальной). Примеры тестов — контрольная и доклад.

**Comment by DedSec256** [comment]
Возможно, нам имеет смысл использовать цветовую шкалу для любого решения любой задачи
