### ISSUE TITLE
Показывать в таблице оценку за предыдущую попытку, если сдана следующая

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#215]
Речь о вот такой ситуации:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/706768/203760444-4b890082-43f4-43fb-b644-d5fe2512fe17.png">
Игорь Антонович имеет оцененную попытку, но мы не можем знать, надо было там чуть-чуть стайлгайд поправить, или всё переписать (и сколько было попыток), пока не кликнем на ячейку и не попадём на экран детальной информации. А Елизавета Олеговна не сдавала новой попытки, так что информация по её успехам доступна сразу же. Неконсистентно.

**Comment by DedSec256** [comment]
Можно было бы сказать, что это так и задумано, чтобы был стимул проверить задание; 

Однако не могу не согласиться, это нужно доработать.

**Comment by DedSec256** [comment]
Исправлено в
https://github.com/InteIIigeNET/HwProj-2.0.1/commit/0479395bcd9a65c202cbc14d4091e42152f54ab8
