### ISSUE TITLE
Запоминать вкладку на странице курса

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#224]
![image](https://user-images.githubusercontent.com/706768/207561269-e38a3e22-2ee1-4d3b-983c-0ed8eeba7588.png)
--- если обновить страницу, попадём на вкладку "домашние задания", что неудобно. Ссылка "Назад к курсу" на экране проверки задания тоже должна вести на таблицу. Так что было бы здорово иметь разные URL для разных вкладок.

**Comment by DedSec256** [comment]
https://github.com/InteIIigeNET/HwProj-2.0.1/pull/227
