### ISSUE TITLE
"Следующее непроверенное решение задачи" показывает попеременно первое и второе сданное непроверенное решение

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#228]
Если решение не проверять и жать на ссылку "Следующее непроверенное решение задачи". А должно, наверное, последовательно переключать все непроверенные решения задачи в каком-то порядке (в идеале по времени сдачи, но в алфавитном порядке авторов тоже ок).

**Comment by DedSec256** [comment]
Сейчас оно работает by-design, показывая следующее _первое_ непроверенное решение в алфавитном порядке. Но не сложно поменять, чтобы переходило по кольцу просто к следующему.

**Comment by yurii-litvinov** [comment]
Это тот случай, когда сделано как написано в ТЗ, но не как хотелось пользователю :) Да, лучше поменять, мне зачем-то это было нужно.
