### ISSUE TITLE
Неудобный скролл в таблице с оценками 

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#234]
Горизонтальный скроллбар только снизу, так что до него надо скроллить:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/706768/229289716-ee8abe41-40e1-43f2-a525-f31ac7373695.png">
Если студентов много, как в курсе на скриншоте, скроллить приходится долго, и "шапка" таблицы при этом становится не видна.

Хочется, наверное, скроллбар иметь всегда видимым, или и сверху таблицы тоже.

Workaround — клик средней кнопкой на таблице, поэтому низкий приоритет.

**Comment by DedSec256** [comment]
https://github.com/InteIIigeNET/HwProj-2.0.1/commit/ee241ae8d03bf9cc4e0a747ea290ffc5daeb45da
