### ISSUE TITLE
"Заморозить" имена студентов в таблице с оценками

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#235]
Если задач в курсе достаточно много, то горизонтальный скролл делает имена студентов невидимыми, как тут:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/706768/229289869-ef76cf97-9ee0-453a-a904-e9dc7cafa93e.png">

Это адски неудобно, поскольку ближе к концу курса приходится постоянно скроллить в начало-конец таблицы и чуть ли не линейку к экрану прикладывать, чтобы никому случайно не в ту клетку балл не поставить. 

Хочется, чтобы имена студентов не скроллились при горизонтальном скролле таблицы.

**Comment by DedSec256** [comment]
https://github.com/InteIIigeNET/HwProj-2.0.1/commit/ee241ae8d03bf9cc4e0a747ea290ffc5daeb45da
