### ISSUE TITLE
Сортировка в фильтрах

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#238]
Фильтры в очереди на проверку сейчас выводят сущности несортированными (или сортированными, но по дате создания), что для достаточно большого числа сущностей делает фильтры бесполезными. Например: 
<img width="849" alt="image" src="https://user-images.githubusercontent.com/706768/229290242-198ffa27-8880-49a6-817a-90b54a0ec98c.png">

Очень сложно тут найти нужного.

**Comment by DedSec256** [comment]
При раскрытом списке можно печатать текст -- будет выбираться вариант с соответствующим префиксом (:
