### ISSUE TITLE
Поиск в фильтрах

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#239]
Фильтры в очереди на проверку в идеале должны иметь текстовое поле поиска, куда можно начать что-то вводить, и значения фильтра отфильтруются по введённой подстроке. Иначе сйечас:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/706768/229290343-21c448d5-1ea2-4bae-bbbf-4f2e3fda4046.png">

Даже если я знаю, что хочу найти, искать довольно долго.

**Comment by DedSec256** [comment]
Если вы напечатаете несколько первых букв при открытом списке, у вас выберется искомый элемент списка

**Comment by yurii-litvinov** [comment]
Это вообще не очевидно, но good enough.
