### ISSUE TITLE
Возможность восстановить пароль

### ISSUE THREAD

**Issue by Volodya-Petrov** [InteIIigeNET/HwProj-2.0.1#249]
## Описание проблемы
Сталкиваюсь второй раз с проблемой, что не могу вспомнить пароль. Хотелось бы иметь возможность восстановить пароль на страничке входа в аккаунт.
## Предлагаемое решение
На страничке авторизации добавить кнопку восстановить пароль, после чего присылается письмо на почту с дальнейшими инструкциями по его восстановлению.

**Comment by DedSec256** [comment]
Добавлено в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/77be0a787737c74e7396f6e6586e89974c02f0a3
