### ISSUE TITLE
Возможность открывать студентов в отдельных вкладках

### ISSUE THREAD

**Issue by uncerso** [InteIIigeNET/HwProj-2.0.1#253]
Проблема:
Открываешь страницу со студентом и его домахой. Начинаешь писать отзыв. Работа большая, к ней много замечаний.
Нашёл проблему -- написал о ней в отзыве.
Нашёл -- дописал ещё немного.
Нашёл -- понял, что можно закопипастить у другого -- ой, ведь ссылка на нужного студента не ссылка, и нельзя так просто открыть его страницу с домахой, при этом оставив открытой текущую страницу.

Самый простой workaround: дублировать текущую вкладку в браузере, переходить на неё, там выбирать нужного студента, и наконец копипастить нужную часть его отзыва.

Не смертельно, но не очень удобно..

**Comment by DedSec256** [comment]
Исправлено в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/400fb72149d76e104cf62471d631e3bde2e24fcb
