### ISSUE TITLE
Сервис курсовых

### ISSUE THREAD

**Issue by DedSec256** [InteIIigeNET/HwProj-2.0.1#26]

**Comment by usik-vladislav** [comment]
Что делает студент:
- Может просмотреть список свободных курсовых
- Может ознакомиться с детальной информацией курсовой
- Там же может подать заявку на эту курсовую
- После одобрения заявки можно загружать работу и презентацию, либо же добавить ссылки на хранилища, где они хранятся
- После рецензии, в случае неготовой работы, студент обновляет то, что нужно
- Имеет возможность загрузить отзыв от научного руководителя. (Если он не зарегистрирован)


Что делает рецензент:
- Может указать типы интересующих работ
- Может просматривать список курсовых и в том числе и по интересующим темам
- На каждую курсовую может ответить да, может быть, нет (+1, +0.5, -1 к мере удовлетворенности соответственно при назначении его на эту курсовую) (период биддинга)
- После утверждения курсовой, написать рецензию и поставить оценки работы и осведомленности
- В случае исправления работы, обновляет рецензию и/или оценку.

Что делает преподаватель:
- Может выкладывать темы курсовых
- Может принимать/отклонять заявки
- Может назначать дедлайны для студентов/рецензентов
- По наступлению дедлайна по биддингу может принять предлагаемого рецензента (все рецензенты предлагаются автоматически минимизируя меру неудовлетворенности)
- Может отказаться от предлагаемого рецензента, просмотреть базу рецензентов и назначить вручную.
- Может подтвердить защиту
- Если преподаватель - научник, может загрузить отзыв

Процесс курсовой:
- Выкладывание темы
- Назначение студента
- Загрузка работы и презентации
- Биддинг
- Назначение рецензента
- Загрузка рецензии
- Исправление при необходимости
- Загрузка отзыва
- Отметка защиты
- Получение зачета
