### ISSUE TITLE
Страница "Курсы" должна отображать вкладку "Ваши курсы" по умолчанию

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#284]
Речь про 
![image](https://github.com/InteIIigeNET/HwProj-2.0.1/assets/706768/793b5314-12b2-4e20-9e9c-2dcb82aa8613)

Количество курсов на вкладке "Все курсы", которая сейчас по умолчанию, пугающе растёт, плюс она показывает и завершённые курсы тоже, плюс в чужой курс я ходил пару раз в жизни, так что можно сэкономить один клик для 99.9% сценариев использования этой страницы

**Comment by DedSec256** [comment]
Тоже об этом думал.
