### ISSUE TITLE
Вкладка "Курсы" в очереди на проверку вроде не нужна

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#287]
Речь про вот это:
![image](https://github.com/InteIIigeNET/HwProj-2.0.1/assets/706768/f8cfc742-01f8-49b7-8e67-6e95011aca95)

В верхнем меню есть кнопка "курсы", так что вкладка на странице очереди проверки кажется избыточной. Тем более что вкладка показывает и завершённые курсы, так что быстро становится не очень полезной.

**Comment by DedSec256** [comment]
Это был эксперимент по выявлению более удобной локации для списка курсов. Можем ли мы предложить что-нибудь полезное сюда вместо вкладки с курсами?

**Comment by yurii-litvinov** [comment]
Пока нет идей. Может, вообще убрать на этой странице вкладки и сделать её конкретно очередью проверки, и всё. Только сохранить счётчик непроверенных работ (и добавить ещё счётчик отфильтрованных непроверенных работ, интересно же).
