### ISSUE TITLE
Запоминать состояние разных полей ввода

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#292]
Пишем комментарий к домашке, в какой-то момент хотим посмотреть, что там было в предыдущих решениях, переключаемся на них, обратно — написанная часть комментария безвозвратно утеряна. У React вроде есть стандартный механизм управления клиентским состоянием, так что можно избегать таких бед, даже не дёргая сервер

**Comment by DedSec256** [comment]
JFYI, можно любую задачу/студента открывать в отдельной вкладке

**Comment by yurii-litvinov** [comment]
Это да, это помогает, но это помнить надо, и ожидать подвоха :)

**Comment by yurii-litvinov** [comment]
А можно даже дёргать сервер, запуская, скажем, раз в 10 секунд автосохранение текущего ввода. Это позволит, например, написать половину комментариев на одном ноуте, половину на другом, ну и не потерять случайно две страницы введённого текста. Технически сложно, но приличные сервисы так умеют, и кажется, что реально повысит юзабилити.

**Comment by DedSec256** [comment]
https://github.com/InteIIigeNET/HwProj-2.0.1/commit/c87a60643df37d26445b292497391a6d1b64776d
