### ISSUE TITLE
Ошибка при вводе несовпадающих паролей

### ISSUE THREAD

**Issue by DronShock** [InteIIigeNET/HwProj-2.0.1#304]
Здравствуйте, я студент первого курса направления "Программная инженерия" Стрельников Андрей Владимирович. На практикуме по ЭВМ наш преподователь, Владимир Кутуев, попросил зарегистрироваться на Вашем сервисе. При регистрации я обнаружил ошибку: если при вводе пароля в двух ячейках они будут не совпадать, то сначала появится уведомление "пароли не совпадают", но при исправлении будет выводиться "Пользователь уже зарегистрирован". При попытке войти, сервис будет сообщать, что пароль или логин неверны. Чтобы решить эту проблему пришлось воспользоваться функцией "Забыли пароль?".

Надеюсь, я никак не помешал своим сообщением о такой несущественной ошибке. Желаю Вам удачи в развитии этого полезного сервиса

**Comment by DedSec256** [comment]
спасибо, что сообщили о проблеме! Исправим.
