### ISSUE TITLE
Возможность отключения уведомлений по почте

### ISSUE THREAD

**Issue by vacmannnn** [InteIIigeNET/HwProj-2.0.1#312]
На почту, указанную при регистрации, приходит уведомления об активности студентов в курсе, которые не всегда нужны.

Нужна возможность отключения рассылки, для того чтобы не было десяток однотипных писем за день

**Comment by DedSec256** [comment]
можно найти на странице уведомлений

![image](https://github.com/InteIIigeNET/HwProj-2.0.1/assets/26364714/57a6a67a-fcd1-4263-bbbb-025a0fda3941)
