### ISSUE TITLE
Скачок решения с одного задания на другое

### ISSUE THREAD

**Issue by IliaSotnikov2005** [InteIIigeNET/HwProj-2.0.1#315]
02.10 сдал задачу "Самый частый элемент", сегодня зашел на сайт (05.10), решение оказалось на задаче "Двоичное представление" с той же датой сдачи. Есть вероятность, что я сам сдал не туда, но было бы странно, если б я этого не заметил.

**Comment by DedSec256** [comment]
Не сумел воспроизвести. Мб помните, как попали на отправку решения задачи, переключали что-либо?

**Comment by DedSec256** [comment]
Переоткройте ишью, если проблема повторится.
