### ISSUE TITLE
Не показывать плашку со временем публикации, если оно уже прошло

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#345]
Например,
<img width="839" alt="image" src="https://github.com/InteIIigeNET/HwProj-2.0.1/assets/706768/c8b6277e-9dd8-4620-87de-510ec1b5c6f8">
11 февраля уже прошло, 20 февраля ещё не наступило, но лекции в интерфейсе преподавателя выглядят одинаково, и вообще не очевидно, что видно сейчас студентам, а что нет. Кажется, раньше "незарелизенные" задачи выделялись цветом и плашкой.

Может, имеет смысл сделать кнопку "вид от студента" в интерфейсе преподавателя, как в Blackboard, чтобы препод мог посмотреть, что сейчас видят записавшиеся на курс, а что нет. И предупреждать об отправке нотификаций, кстати :)

**Comment by DedSec256** [comment]
Сделано в https://github.com/InteIIigeNET/HwProj-2.0.1/commit/623023e439d77fde815fa445e42e6b78d824cb96
