### ISSUE TITLE
Сделать для преподавателя удобный способ выгрузить всех студентов на курсе

### ISSUE THREAD

**Issue by yurii-litvinov** [InteIIigeNET/HwProj-2.0.1#399]
Часто бывает нужно какую-нибудь табличку завести (типа записи на доклады, таблички с баллами за экзамен и т.п.), хочется откуда-то скопипастить всех студентов, кто хотя бы записался на курс на HwProj. Если копипастить из таблицы с баллами, оно копипастится вместе с баллами, что неудобно. Хочется иметь возможность выделить всех и вставить.

Быстрое и грязное решение — добавить модальное окошко со списком, но можно потерпеть до того, как появится какая-нибудь админка курса (**если** появится), где можно будет удалять/редактировать студентов, и копипастить оттуда.

**Comment by DedSec256** [comment]
Можно скопировать таблицу и даже вставить её с правильным форматированием в Google Doc. Переоткройте issue, если это не решение.

**Comment by yurii-litvinov** [comment]
Good enough, хотя и требует промежуточного копирования в таблицу и затем уже копирования из таблицы только столбца с ФИО. Для случая использования, где мы быстро хотим, например, скинуть список студентов в Telegram, неудобно, но жить можно и есть более приоритетные задачи, поэтому ок.
